server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: offer-service
          uri: lb://OFFER-SERVICE
          predicates:
            - Path=/offer/**
          filters:
            - AuthenticationFilter
            - PreserveHostHeader
        - id: jwt-service
          uri: lb://JWT-SERVICE
          predicates:
            - Path=/jwt/**

        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
                - Path=/email/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - PreserveHostHeader

        - id: home-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/
          filters:
            - PreserveHostHeader
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
            - PreserveHostHeader
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    # This helps Eureka identify the container by its name/IP in the Docker network
    prefer-ip-address: true