server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: offer-service
          uri: lb://OFFER-SERVICE
          predicates:
            - Path=/offer/**
          filters:
            - AuthenticationFilter
            - PreserveHostHeader
        - id: jwt-service
          uri: lb://JWT-SERVICE
          predicates:
            - Path=/jwt/**

        - id: email-service
          uri: lb://EMAIL-SERVICE
          predicates:
                - Path=/email/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - PreserveHostHeader

        - id: home-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/
          filters:
            - PreserveHostHeader
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - AuthenticationFilter
            - PreserveHostHeader
  profiles:
    docker:
      eureka:
        client:
          service-url:
            defaultZone: http://eureka-server:8761/eureka/
    local:
      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8761/eureka/